apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: vertliba-ru-tls
spec:
  secretName: vertliba-ru
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: vertliba.ru
  dnsNames:
    - vertliba.ru
    - www.vertliba.ru
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - vertliba.ru
          - www.vertliba.ru
